"""Generate raw inventory, quality findings, and source dictionary without EDA/modeling."""

import json
import logging

import pandas as pd

from readmit_iq.config import configure_logging, load_config
from readmit_iq.data.download import verify_file
from readmit_iq.data.load_data import ID_COLUMNS, load_id_mapping, load_raw
from readmit_iq.data.validate import binary_target, validate_raw

LOGGER = logging.getLogger(__name__)


def column_profile(frame: pd.DataFrame) -> pd.DataFrame:
    """Distinguish source missing markers, structural absence, and parser nulls."""
    rows = []
    for name, series in frame.items():
        text = series.astype("string")
        question = int(text.eq("?").sum())
        blank = int(text.eq("").sum())
        native = int(series.isna().sum())
        row = {
            "column": name,
            "loaded_dtype": str(series.dtype),
            "unique_values_including_markers": int(series.nunique(dropna=False)),
            "question_mark_count": question,
            "blank_count": blank,
            "parser_null_count": native,
            "missing_marker_pct": round(100 * (question + blank + native) / len(frame), 4),
            "literal_None_count": int(text.eq("None").sum()),
            "min": None,
            "max": None,
        }
        if pd.api.types.is_numeric_dtype(series):
            row.update({"min": int(series.min()), "max": int(series.max())})
        rows.append(row)
    return pd.DataFrame(rows)


def summarize(frame: pd.DataFrame, profile: pd.DataFrame, validation: dict) -> dict:
    patient_counts = frame.patient_nbr.value_counts()
    target = binary_target(frame.readmitted)
    return {
        "rows": len(frame),
        "columns": len(frame.columns),
        "candidate_features": len(frame.columns) - len(ID_COLUMNS) - 1,
        "id_columns": ID_COLUMNS,
        "unique_patients": int(patient_counts.size),
        "patients_with_multiple_encounters": int(patient_counts.gt(1).sum()),
        "encounters_from_repeat_patients": int(patient_counts[patient_counts.gt(1)].sum()),
        "additional_encounters_beyond_one_per_patient": int(len(frame) - patient_counts.size),
        "max_encounters_per_patient": int(patient_counts.max()),
        "target_counts": {str(k): int(v) for k, v in frame.readmitted.value_counts().items()},
        "positive_count": int(target.sum()),
        "negative_count": int(len(target) - target.sum()),
        "positive_rate": float(target.mean()),
        "negative_to_positive_ratio": float((len(target) - target.sum()) / target.sum()),
        "constant_columns": profile.loc[
            profile.unique_values_including_markers.eq(1), "column"
        ].tolist(),
        "loaded_dtype_counts": frame.dtypes.astype(str).value_counts().to_dict(),
        "native_null_total": int(frame.isna().sum().sum()),
        "blank_total": int(profile.blank_count.sum()),
        "question_mark_total": int(profile.question_mark_count.sum()),
        "validation": validation,
    }


def render_report(summary: dict, profile: pd.DataFrame) -> str:
    s = summary
    checks = s["validation"]
    lines = [
        "# Phase 1: raw-data inspection",
        "",
        "Generated by `python -m readmit_iq.data.inspect` from checksum-verified UCI files.",
        "No rows or columns were removed, no values were imputed, and no split or model was fit.",
        "The binary target is computed in memory only to count labels.",
        "",
        "## Inventory",
        "",
        "| Measure | Observed |",
        "|---|---:|",
        f"| Encounters | {s['rows']:,} |",
        f"| Columns | {s['columns']} |",
        f"| Candidate features before review | {s['candidate_features']} |",
        f"| Unique patients | {s['unique_patients']:,} |",
        f"| Patients with multiple encounters | {s['patients_with_multiple_encounters']:,} |",
        f"| Encounters belonging to repeat patients | {s['encounters_from_repeat_patients']:,} |",
        f"| Additional encounters beyond one per patient | "
        f"{s['additional_encounters_beyond_one_per_patient']:,} |",
        f"| Maximum encounters for one patient | {s['max_encounters_per_patient']} |",
        f"| Exact duplicate rows | {checks['duplicate_rows']} |",
        f"| Duplicate encounter IDs | {checks['duplicate_encounter_ids']} |",
        "",
        "The 50 raw columns comprise 47 candidate features, two identifiers and one target.",
        "Identifiers and diagnosis codes are explicitly loaded as strings. Integer admission/",
        "discharge/source codes remain unchanged and are semantically categorical.",
        "",
        "## Target counts",
        "",
        "| Source label | Encounters | Percent |",
        "|---|---:|---:|",
    ]
    for label in ["<30", ">30", "NO"]:
        count = s["target_counts"][label]
        lines.append(f"| `{label}` | {count:,} | {100 * count / s['rows']:.2f}% |")
    lines += [
        "",
        f"Positive rate: **{100 * s['positive_rate']:.2f}%**. "
        f"Negative-to-positive ratio: **{s['negative_to_positive_ratio']:.2f}:1**.",
        "Positive means the provided `<30` label. Both `>30` and `NO` are negative.",
        "`NO` means no recorded readmission. It does not prove absence of readmission elsewhere.",
        "The literal labels do not resolve the exact day-30 boundary; raw dates are unavailable.",
        "No resampling, class weighting, or threshold choice is made at this stage.",
        "",
        "## Missingness",
        "",
        "| Column | `?` count | Percent |",
        "|---|---:|---:|",
    ]
    for row in profile.sort_values("question_mark_count", ascending=False).itertuples():
        if row.question_mark_count:
            lines.append(
                f"| `{row.column}` | {row.question_mark_count:,} | "
                f"{100 * row.question_mark_count / s['rows']:.2f}% |"
            )
    lines += [
        "",
        f"Parser nulls: {s['native_null_total']:,}; blank cells: {s['blank_total']:,}.",
        "These zero counts do not mean complete data: the source encodes missingness as `?`",
        "and administrative unknown categories. Those are reported separately in `summary.json`.",
        "",
        "| Lab column | `None` (not measured) | Percent |",
        "|---|---:|---:|",
    ]
    for row in profile.loc[profile.column.isin(["A1Cresult", "max_glu_serum"])].itertuples():
        lines.append(
            f"| `{row.column}` | {row.literal_None_count:,} | "
            f"{100 * row.literal_None_count / s['rows']:.2f}% |"
        )
    lines += [
        "",
        "`None` is a documented not-measured category, distinct from unknown results.",
        "Do not let default CSV NA parsing erase this information.",
        "",
        "## Quality checks and decisions still needed",
        "",
        f"- Source-contract validation passed: **{checks['passed']}**.",
        "- Documented age bands, integer count bounds, and code mappings were checked.",
        "  Zero violations were found; this is not a full clinical plausibility assessment.",
        "- Constant columns: " + ", ".join(f"`{c}`" for c in s["constant_columns"]) + ".",
        f"- Gender `Unknown/Invalid`: {checks['unknown_invalid_gender']} records, preserved.",
    ]
    terminal = sum(v["count"] for v in checks["death_or_hospice_dispositions"].values())
    lines += [
        f"- Death/hospice codes identify **{terminal:,} encounters**. Decide the eligible",
        "  cohort before modeling. The original study excluded these; this audit preserves them.",
        "- Patient repetition requires a patient-grouped evaluation strategy in a later phase.",
        "  IDs are grouping/audit keys, not candidate predictors. No split was created.",
        "- The supplied columns contain no admission/discharge dates or hospital identifier.",
        "  Do not treat encounter ID order as validated chronology. Temporal and hospital holdouts",
        "  cannot be established from this extract alone.",
        "- Proposed prediction time is discharge: utilization during the encounter and discharge",
        "  disposition need an availability review. They would leak future information for an",
        "  admission-time prediction task. No final feature eligibility has been decided.",
        "- Ranges and cardinality are in `column_profile.csv`; small-category counts and mapping",
        "  descriptions are in `category_counts.json` and `id_mapping.json`. Extreme counts are",
        "  observations to investigate later, not grounds for automatic outlier removal.",
        "",
        "## Scope and next decision",
        "",
        "Phase 1 ends here. Next, agree on the discharge cohort and inspect missingness meanings",
        "before question-driven EDA. No EDA charts, imputation, feature engineering, train/test",
        "split, fitted baseline, or model performance claims have been produced.",
        "",
        "See `docs/dataset_selection.md` for source comparisons, provenance and limitations, and",
        "`docs/data_dictionary.md` for source descriptions and observed raw columns.",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    configure_logging()
    config = load_config()
    for name, checksum in config.dataset.file_sha256.items():
        verify_file(config.raw_dir / name, checksum)
    frame = load_raw(config.raw_dir / "diabetic_data.csv")
    mappings = load_id_mapping(config.raw_dir / "IDS_mapping.csv")
    validation = validate_raw(frame, config, mappings)
    config.report_dir.mkdir(parents=True, exist_ok=True)
    (config.report_dir / "validation.json").write_text(json.dumps(validation, indent=2) + "\n")
    if not validation["passed"]:
        raise ValueError(f"Raw validation failed: {validation['errors']}")
    profile = column_profile(frame)
    summary = summarize(frame, profile, validation)
    profile.to_csv(config.report_dir / "column_profile.csv", index=False)
    categories = {
        column: {str(k): int(v) for k, v in frame[column].value_counts(dropna=False).items()}
        for column in frame.columns
        if frame[column].nunique() <= 50 and column not in ID_COLUMNS
    }
    for name, payload in [
        ("summary", summary),
        ("id_mapping", mappings),
        ("category_counts", categories),
    ]:
        (config.report_dir / f"{name}.json").write_text(json.dumps(payload, indent=2) + "\n")
    (config.report_dir / "raw_data_report.md").write_text(render_report(summary, profile))
    LOGGER.info(
        "Raw inspection complete: %s rows, %.4f positive rate; reports in %s",
        len(frame),
        summary["positive_rate"],
        config.report_dir,
    )


if __name__ == "__main__":
    main()
